### ISSUE TITLE
Repository's website link is 404

### ISSUE THREAD

**Issue by azu** [guybedford/proposal-dynamic-modules#12]
![dynamic-modules dynamic modules proposal for ecmascript 2018-12-23 14-18-18](https://user-images.githubusercontent.com/19714/50380972-b9f5f380-06bd-11e9-8ec2-5fc959187d35.png)

Currently, Repository's "website" link is 404.

https://guybedford.github.io/proposal-dynamic-modules/
would be
https://nodejs.github.io/dynamic-modules/

**Comment by guybedford** [comment]
Thanks @azu for noting this. Unfortunately I don't have the permission to change this link to the correct one at https://nodejs.github.io/dynamic-modules/, but will see if I can get someone to take a look.

**Comment by MylesBorins** [comment]
Fixed
