### ISSUE TITLE
Consideration: Undefined names don't throw statically

### ISSUE THREAD

**Issue by SMotaal** [guybedford/proposal-dynamic-modules#6]
I am not sure if I missed it, but I think dynamic modules are a good place to argue against static errors for `import { notdefined } from 'that-dynamic-module'` and instead this could simply result in a local binding to the contextual `undefined`. **Only for imports from dynamic module namespaces.**

Why this makes sense semantically, it is similar to `import * as namespace from 'that-dynamic-module'; const { notdefined } = namespace;` but without the ability to do something like `const { notdefined = fallback } = namespace;` which would really complicate semantic code analysis.

Why this makes sense practically, well, it is a dynamic module.

Any thoughts?

**Comment by guybedford** [comment]
Note that namespaces don't reflect undefined values, as Object.keys(namespace) will provide a list of exported names. If we allow importers to define what names are defined this means that `Object.keys(namespace)` is now dependent on who is importing this module and how they are importing it determining if `namespace` has a `someNonExistingExport` name.

**Comment by SMotaal** [comment]
So I was coming from a different notion that a dynamic module's declared name would be undefined until set. Which made me think of all names being undefined until declared and set. To me, this is abstractionally more sound and potentially non-breaking to the concrete concepts that reflect all non-ES modules currently interfacing with JavaScript, but I could be wrong.

Because I default to thinking on the abstract side (to a fault), I think more of this as a future feature of the JavaScript, which are Dynamic Modules that make it possible for people to use as a building block for completely novel ideas. This makes me hope that for some scenarios like prototyping and development, they would be able to leave names that import from a module if they comment out that particular export (assuming they also factor in for undefined of course). I could also extend this to `hot reloading` but I am probably not the best advocate for this whole can.

**Comment by SMotaal** [comment]
Seems irrelevant at this point
