### ISSUE TITLE
Consideration: Default === Star for dynamic modules

### ISSUE THREAD

**Issue by SMotaal** [guybedford/proposal-dynamic-modules#7]
Due to the immutable nature of the `default` export, which works well for static modules, it may be possible to avoid introducing complexities surrounding the potential of dynamically set `default` in dynamic modules if instead both `default` and `*` immutably bind to the module namespace.

This comes with the downside that `default` can never be a function, which is not an encouraging thought at face value, but it might  not be as bad as it sounds.

**Comment by ljharb** [comment]
It would be much worse than it sounds; the default export being a function is a critical use case for many both in the React ecosystem, and outside of it (including much of npm).

**Comment by SMotaal** [comment]
I realize that, the question is, will those be dynamic-modules?

**Comment by ljharb** [comment]
The entire point of dynamic modules is to enable named imports from CJS modules - a great many of these have a conceptual default export, with or without conceptual named exports.

I’m not sure how what you’re suggesting here helps anything, and it seems like it would preclude the most important property: compatibility with most of the world’s reusable javascript. Can you help me understand what I’m missing?

**Comment by SMotaal** [comment]
Obviously if there is a need and there is no benefit to adding such a limitation, then it makes no sense 👍
